### PR TITLE
added Crack Traxxxx, crazy cinema story, Daily Lunch Special ~DeliciousREMIX~

### PR DESCRIPTION
**Pull request by Dessard**

### CODE REVIEW

**Comment by Schinizer** [comment]
For Crazy cinema story, the FX track is offset wrongly. The editor cannot take negative values for offset I think.

**Comment by Dessard** [comment]
Huh, it worked just fine for me, but I'll edit the sound files and resubmit it.

**Comment by Schinizer** [comment]
Try playing at half BPM. Its hard to spot but yeah.

**Comment by Dessard** [comment]
Well, now it seems to be almost a second off like it was before I did the offset.  I guess that negative value really messes things up.

**Comment by Dessard** [comment]
Wow, looks like the exh and nofx tracks are slightly different speeds.  That's not great; going to try to fix that first.

**Pull request closed without merging**
